/**
 *
 */

package com.experimental.maindata.model;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table staff
 * @Edit_Description:
 * @Create_Version:login-demo 1.0
 *
 * @mbg.generated do_not_delete_during_merge 2020-09-26 19:30:02
 */
public class Staff implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户名
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.username
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.password
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private String password;

    /**
     * Database Column Remarks:
     *   加密盐
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.salt
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private String salt;

    /**
     * Database Column Remarks:
     *   邮箱
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.email
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private String email;

    /**
     * Database Column Remarks:
     *   手机号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.phone
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   状态：0禁用；1正常
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.status
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   机构id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.dept_id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private Long deptId;

    /**
     * Database Column Remarks:
     *   创建人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.create_id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private Long createId;

    /**
     * Database Column Remarks:
     *   创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.create_time
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.update_id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private Long updateId;

    /**
     * Database Column Remarks:
     *   修改时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.update_time
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除：0正常，1删除
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.is_delete
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id
     *
     * @return the value of staff.id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id
     *
     * @param id the value for staff.id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.username
     *
     * @return the value of staff.username
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.username
     *
     * @param username the value for staff.username
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.password
     *
     * @return the value of staff.password
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.password
     *
     * @param password the value for staff.password
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.salt
     *
     * @return the value of staff.salt
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.salt
     *
     * @param salt the value for staff.salt
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.email
     *
     * @return the value of staff.email
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.email
     *
     * @param email the value for staff.email
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.phone
     *
     * @return the value of staff.phone
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.phone
     *
     * @param phone the value for staff.phone
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.status
     *
     * @return the value of staff.status
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.status
     *
     * @param status the value for staff.status
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.dept_id
     *
     * @return the value of staff.dept_id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.dept_id
     *
     * @param deptId the value for staff.dept_id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.create_id
     *
     * @return the value of staff.create_id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.create_id
     *
     * @param createId the value for staff.create_id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.create_time
     *
     * @return the value of staff.create_time
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.create_time
     *
     * @param createTime the value for staff.create_time
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.update_id
     *
     * @return the value of staff.update_id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.update_id
     *
     * @param updateId the value for staff.update_id
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.update_time
     *
     * @return the value of staff.update_time
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.update_time
     *
     * @param updateTime the value for staff.update_time
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.is_delete
     *
     * @return the value of staff.is_delete
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.is_delete
     *
     * @param isDelete the value for staff.is_delete
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}