/**
 *
 */

package com.experimental.maindata.mapper;

import com.experimental.maindata.model.MainDict;
import com.experimental.maindata.model.MainDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table main_dict
 * @Edit_Description:
 * @Create_Version:login-demo 1.0
 *
 * @mbg.generated do_not_delete_during_merge 2020-09-26 19:30:02
 */
public interface MainDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    long countByExample(MainDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByExample(MainDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insert(MainDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insertSelective(MainDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    List<MainDict> selectByExample(MainDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    MainDict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExampleSelective(@Param("record") MainDict record, @Param("example") MainDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExample(@Param("record") MainDict record, @Param("example") MainDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKeySelective(MainDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_dict
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKey(MainDict record);
}