/**
 *
 */

package com.experimental.maindata.mapper;

import com.experimental.maindata.model.MenuRoleRelationship;
import com.experimental.maindata.model.MenuRoleRelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table menu_role_relationship
 * @Edit_Description:
 * @Create_Version:login-demo 1.0
 *
 * @mbg.generated do_not_delete_during_merge 2020-09-26 19:30:02
 */
public interface MenuRoleRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    long countByExample(MenuRoleRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByExample(MenuRoleRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insert(MenuRoleRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insertSelective(MenuRoleRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    List<MenuRoleRelationship> selectByExample(MenuRoleRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    MenuRoleRelationship selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExampleSelective(@Param("record") MenuRoleRelationship record, @Param("example") MenuRoleRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExample(@Param("record") MenuRoleRelationship record, @Param("example") MenuRoleRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKeySelective(MenuRoleRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKey(MenuRoleRelationship record);
}