/**
 *
 */

package com.experimental.maindata.mapper;

import com.experimental.maindata.model.RoleDeptRelationship;
import com.experimental.maindata.model.RoleDeptRelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_dept_relationship
 * @Edit_Description:
 * @Create_Version:login-demo 1.0
 *
 * @mbg.generated do_not_delete_during_merge 2020-09-26 19:30:02
 */
public interface RoleDeptRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    long countByExample(RoleDeptRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByExample(RoleDeptRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insert(RoleDeptRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insertSelective(RoleDeptRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    List<RoleDeptRelationship> selectByExample(RoleDeptRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    RoleDeptRelationship selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExampleSelective(@Param("record") RoleDeptRelationship record, @Param("example") RoleDeptRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExample(@Param("record") RoleDeptRelationship record, @Param("example") RoleDeptRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKeySelective(RoleDeptRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dept_relationship
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKey(RoleDeptRelationship record);
}