/**
 *
 */

package com.experimental.maindata.mapper;

import com.experimental.maindata.model.StaffRole;
import com.experimental.maindata.model.StaffRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table staff_role
 * @Edit_Description:
 * @Create_Version:login-demo 1.0
 *
 * @mbg.generated do_not_delete_during_merge 2020-09-26 19:30:02
 */
public interface StaffRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    long countByExample(StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByExample(StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insert(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insertSelective(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    List<StaffRole> selectByExample(StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    StaffRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExampleSelective(@Param("record") StaffRole record, @Param("example") StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExample(@Param("record") StaffRole record, @Param("example") StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKeySelective(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKey(StaffRole record);
}