/**
 *
 */

package com.experimental.maindata.mapper;

import com.experimental.maindata.model.StaffDept;
import com.experimental.maindata.model.StaffDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table staff_dept
 * @Edit_Description:
 * @Create_Version:login-demo 1.0
 *
 * @mbg.generated do_not_delete_during_merge 2020-09-26 19:30:02
 */
public interface StaffDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    long countByExample(StaffDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByExample(StaffDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insert(StaffDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int insertSelective(StaffDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    List<StaffDept> selectByExample(StaffDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    StaffDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExampleSelective(@Param("record") StaffDept record, @Param("example") StaffDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByExample(@Param("record") StaffDept record, @Param("example") StaffDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKeySelective(StaffDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_dept
     * @Edit_Description:
     * @Create_Version:login-demo 1.0
     *
     * @mbg.generated 2020-09-26 19:30:02
     */
    int updateByPrimaryKey(StaffDept record);
}